version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-lambda-tf"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bs1ehtme4d8m"
s3_prefix = "aws-lambda-tf"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=938385028059.dkr.ecr.ap-northeast-1.amazonaws.com/awslambdatf170f7743/helloworldfunction19d43fc4repo"]
